
const listItems = [
  "Su sonrisa que ilumina mi día.",
  "La forma en como se ponen sus ojos cuando sonríe.",
  "Su risa contagiosa.",
  "Su paciencia infinita conmigo.",
  "Su manera de apoyarme siempre.",
  "Cuando me abrazas.",
  "Lo linda que te ves cuando te enojas.",
  "Cómo se esfuerzas por lo que amas.",
  "Su voz dulce y calmada.",
  "Cuando se emocionas por cosas pequeñas.",
  "Sus ocurrencias inesperadas.",
  "Lo bien que cocinas.",
  "Cuando me haces reír sin intentarlo.",
  "Su amor por los niños.",
  "Lo hermosa que eres por dentro y por fuera.",
  "Cómo me hace sentir especial.",
  "Su ternura al despertar.",
  "Cómo me entiende sin que le diga nada.",
  "La forma de sus cachetes.",
  "Su manera única de ver el mundo.",
  "Su pasión por lo que haces.",
  "Cuando me dice corazón o bello.",
  "Su vestimenta.",
  "Lo bien que te ves con cualquier cosa.",
  "Cómo me hace sentir con sus mensajes.",
  "Cuando te preocupas por mí.",
  "Su forma de hablarme con amor.",
  "Sus abrazos.",
  "Cómo hace que todo sea mejor.",
  "Tu lado divertido y juguetón.",
  "Cuando me dices que me quieres.",
  "Sus ojos cafecitos.",
  "Cómo es con tu familia.",
  "Su inteligencia que admiro.",
  "Sus ojitos cuando me miran.",
  "La confianza que me das.",
  "Su aroma que me encanta.",
  "Cuando me sorprendes con mensajes lindos.",
  "Su forma de tratar a los demás.",
  "Cuando se emociona con los detalles que le hago.",
  "Su sinceridad.",
  "Su valentía ante los problemas.",
  "Su forma de cuidar a los demás.",
  "Cómo me hace sentir querido.",
  "Su entusiasmo por la vida.",
  "Cuando me cuentas sus sueños.",
  "Su forma de amar sin límites.",
  "Su creatividad.",
  "Cuando bromeamos.",
  "La forma en como reacciona a mis piropos.",
  "Lo orgullosa que estás de mí.",
  "Su forma de enseñarme cosas.",
  "Cuando comparte su día día conmigo.",
  "Su atención a los detalles.",
  "Su perseverancia.",
  "Su energía tan positiva.",
  "Lo bien que nos entendemos.",
  "Sus manossssssss.",
  "Tus labios hermosos.",
  "Su confianza en mí.",
  "Su forma de vestirte.",
  "Tu humildad.",
  "Cuando me mira.",
  "Cuando me manda fotos de lo que hace.",
  "Su curiosidad.",
  "Su risa en los momentos tontos.",
  "Cuando me haces sentir invencible.",
  "Su nobleza.",
  "Lo mucho que te amo.",
  "Su manera de celebrar mis logros.",
  "Tu respeto hacia los demás.",
  "Cuando me espera con ansias.",
  "Cuando decimos dunderas.",
  "Sus pláticas de la nada.",
  "Sus bromas locas.",
  "Cuando me escuchas con atención.",
  "Su forma de ser tú misma.",
  "Cuando se pones celosa.",
  "Sus cachetitos hermosos nuevamente.",
  "Cuando me dice que soy guapo.",
  "Cuando me miras en silencio y sonríes.",
  "Su mirada cómplice.",
  "Su forma de ser fuerte cuando lo necesitas.",
  "Su forma de demostrar amor sin palabras.",
  "Cuando hablamos por horas.",
  "Su forma en como me trata.",
  "Cuando me haces sentir el hombre más afortunado.",
  "Sus ideas locas.",
  "Tu forma de decir “te amo”.",
  "Sus mensajitos tiernos.",
  "Sus buenas noches con cariño.",
  "Cuando me dice buenos días.",
  "Cuando me manda audios.",
  "Cuando me tomas la mano fuerte.",
  "Su voz cuando se enoja.",
  "Su manera de corregirme con amor.",
  "Su autenticidad.",
  "Su lealtad.",
  "Tu forma de verme como nadie más lo hace.",
  "Cómo llena mi vida de color.",
  "Su forma de hacerme sentir afortunado.",
  "Su existencia entera.",
  "Simplemente usted, mi chelita, mi maestra favorita, simplemente Onix."
];

const ul = document.getElementById("list");

listItems.forEach((item, index) => {
  const li = document.createElement("li");
  li.textContent = `${index + 1}. ${item}`;
  ul.appendChild(li);
});
